### ISSUE TITLE
First deliverables ready for review

### ISSUE THREAD

**Issue by jcmann** [mad-java-ent-f21/teamCatLady#1]
Hi @pawaitemadisoncollege ! Our first round of documents are ready for review.

**Comment by pawaitemadisoncollege** [comment]
@jcmann @jeliceiri @kmracchini Your team has an _excellent_ start!  Your problem statement, solution description, charter and resume all demonstrate careful thought and attention to the details. The scope of this project is well-sized based on the current number of resources/operations and response types.

Questions: 
- [x] The service will provide the ability to add a president, should there be a POST listed in the service calls?
- [x] If one of the target consumers might be a trivia application, would the president's "number" also be helpful - being able to answer who was the 5th president, for example? If this is scoped out for some reason, it might be nice to address it. Perhaps listing what might be coming in "V2" as you pull together your final documentation  ;)   

Suggestion: 
- [x] If you will have any properties or config files that are "developer-specific" it might be helpful to add them to gitignore sooner than later. 

Looking forward to seeing this built out!
